### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by fennectech**

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks great! Thanks a lot.

**Comment by RobLoach** [comment]
Mind updating to No-Intro naming?
https://datomatic.no-intro.org/index.php?page=show_record&s=47&n=0901

```
Pokemon - Crystal Version (USA, Europe) (Rev 1)
Pokemon - Crystal Version (USA, Europe)
```

**Comment by RobLoach** [comment]
This one looks a bit higher quality :wink: 

gbc_pokemoncrystalversion

**Comment by fennectech** [comment]
Just comitted it :)

**Pull request merged**
