### PR TITLE
Replaced boxart

### PR DESCRIPTION
**Pull request by Hawaka743**
Replaced boxart with region specific versions.

### CODE REVIEW

**Comment by RobLoach** [comment]
Could you compress the images? They're both half a meg currently.

**Comment by RobLoach** [comment]
Eh, they're fine.

**Comment by Hawaka743** [comment]
I always use gimp to export (convert) the images into png, whit the compression rate set to the highest value. Maybe they could be compressed more, with software made specifically for compressing images (of which I don't know any).

**Comment by RobLoach** [comment]
These are great! Thanks so much for updating the images.

**Pull request merged**
