### PR TITLE
add files to gbc because demo ver of game

### PR DESCRIPTION
**Pull request by Riot20058**
going added dragonbome dx to master build

### CODE REVIEW

**Comment by Riot20058** [comment]
@RobLoach @alfrix @MarcoEstevez guys added this files into database for games of Dragonborne DX (GBC) - Demo rom name how given out for homebrew game site.

**Comment by RobLoach** [comment]
Would you mind making sure the images are at most 512px wide? Thanks!

**Comment by Riot20058** [comment]
How do you do this

**Comment by Riot20058** [comment]
> Would you mind making sure the images are at most 512px wide? Thanks!

Dragonborne_DX_-_DEMO_2023-04-29
Dragonborn-DX-Main-Logo-1200x675

**Comment by Riot20058** [comment]
> Would you mind making sure the images are at most 512px wide? Thanks!

plsese add files post ont last realiy for thia because no clue meant doing here.

**Comment by Riot20058** [comment]
just added 3 and 4 boxart  because one set 512px for both of thier.

**Comment by Riot20058** [comment]
@RobLoach make sure rom name is Dragonborne_DX_-_DEMO_2023-04-29 because added this so work with NSUI which need right and rom name for demo ver of Dragonborne game

**Comment by Riot20058** [comment]
@RobLoach going to wait final ver of game come in q3 2023 beforce added it to batabase

**Comment by RobLoach** [comment]
Exciting! I'll have to check it out. Been looking for a game to pick up.

**Pull request closed without merging**
